import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [guillo, setGuillo] = useState("Equipo 1");
  const [jerogol, setJeroGol] = useState("Equipo 2");

  const [countG, setCountG] = useState(0);

  function counterplusG() {
    setCountG(countG + 1);
  }

  function counterlessG() {
    setCountG(countG - 1);
  }

  const [countJ, setCountJ] = useState(0);

  function counterplusJ() {
    setCountJ(countJ + 1);
  }

  function counterlessJ() {
    setCountJ(countJ - 1);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="containerCounter">
        <div>
 
            <input
              value={guillo}
              onChange={(e) => {
                setGuillo(e.target.value);
              }}
            ></input>

          <p
            onClick={() => {
              counterplusG();
            }}
          >
            +
          </p>
          <p className="count">{countG}</p>
          <p
            onClick={() => {
              counterlessG();
            }}
          >
            -
          </p>
        </div>
        <div>
          <input
            value={jerogol}
            onChange={(e) => {
              setJeroGol(e.target.value);
            }}
          ></input>
          <p
            onClick={() => {
              counterplusJ();
            }}
          >
            +
          </p>
          <p className="count">{countJ}</p>
          <p
            onClick={() => {
              counterlessJ();
            }}
          >
            -
          </p>
        </div>
      </div>
    </div>
  );
}
